# Generated by Django 3.2.15 on 2022-09-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_pie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pie',
            name='voteflag',
            field=models.IntegerField(),
        ),
    ]
