# Generated by Django 3.2.15 on 2022-09-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_pie_voteflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='pie',
            name='Users',
            field=models.ManyToManyField(related_name='pies', to='app1.User'),
        ),
    ]
